// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeCatalog(arg1:main.CatalogRequest):Promise<main.CatalogAnalysis>;

export function ClearChapterCaches(arg1:Array<string>):Promise<Array<main.CacheEntry>>;

export function ClearNovelCaches(arg1:Array<string>):Promise<Array<main.NovelCacheEntry>>;

export function DeleteNovel(arg1:string):Promise<main.AppState>;

export function DeleteRule(arg1:string):Promise<main.AppState>;

export function ExportNovel(arg1:main.ExportRequest):Promise<main.ExportResult>;

export function ExportNovelAdvanced(arg1:main.ExportRequest):Promise<main.ExportResult>;

export function ListChapterCaches():Promise<Array<main.CacheEntry>>;

export function ListNovelCaches():Promise<Array<main.NovelCacheEntry>>;

export function LoadState():Promise<main.AppState>;

export function ReadChapter(arg1:main.ChapterReadRequest):Promise<main.ChapterReadResult>;

export function SaveNovel(arg1:main.Novel):Promise<main.AppState>;

export function SaveRule(arg1:main.SiteRule):Promise<main.AppState>;
