// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeCatalog(arg1) {
  return window['go']['main']['App']['AnalyzeCatalog'](arg1);
}

export function ClearChapterCaches(arg1) {
  return window['go']['main']['App']['ClearChapterCaches'](arg1);
}

export function ClearNovelCaches(arg1) {
  return window['go']['main']['App']['ClearNovelCaches'](arg1);
}

export function DeleteNovel(arg1) {
  return window['go']['main']['App']['DeleteNovel'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function ExportNovel(arg1) {
  return window['go']['main']['App']['ExportNovel'](arg1);
}

export function ExportNovelAdvanced(arg1) {
  return window['go']['main']['App']['ExportNovelAdvanced'](arg1);
}

export function ListChapterCaches() {
  return window['go']['main']['App']['ListChapterCaches']();
}

export function ListNovelCaches() {
  return window['go']['main']['App']['ListNovelCaches']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function SaveNovel(arg1) {
  return window['go']['main']['App']['SaveNovel'](arg1);
}

export function SaveRule(arg1) {
  return window['go']['main']['App']['SaveRule'](arg1);
}
